# Generated by Django 5.1.2 on 2024-10-20 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=15, unique=True)),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('online', models.BooleanField(default=False)),
                ('platform', models.CharField(default='Unknown', max_length=15)),
                ('is_logged_in', models.BooleanField(default=False)),
                ('architecture', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('keep_writebacks', models.BooleanField(default=True)),
                ('one_time_reboot', models.BooleanField(default=False)),
                ('enable_one_time_reboot', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('size', models.IntegerField(default=0)),
                ('zfs_volume', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('is_boot', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InitrdFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ipxe/initrds/')),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('path', models.CharField(max_length=200, unique=True)),
                ('block', models.CharField(max_length=200, unique=True)),
                ('size', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClientSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zfs_volume', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='pxe.client')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=1000)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('date_executed', models.DateTimeField(blank=True, null=True)),
                ('is_executed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pxe.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pxe.image'),
        ),
        migrations.CreateModel(
            name='BootImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('kernel', models.FileField(upload_to='ipxe/kernels/')),
                ('default', models.BooleanField(default=False)),
                ('initrds', models.ManyToManyField(blank=True, related_name='menu_entries', to='pxe.initrdfile')),
            ],
        ),
        migrations.CreateModel(
            name='iSCSiTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iqn', models.CharField(max_length=255)),
                ('volume', models.CharField(max_length=255)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='pxe.client')),
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pxe.clientsnapshot')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='zfs_dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pxe.pool'),
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('zfs_volume', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='pxe.image')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='clientsnapshot',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_snapshots', to='pxe.snapshot'),
        ),
    ]
